"""mechaber table

Revision ID: 1fa1545abbd1
Revises: 
Create Date: 2019-10-02 07:44:21.840173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa1545abbd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechaber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mechabername', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechaber_mechabername'), 'mechaber', ['mechabername'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mechaber_mechabername'), table_name='mechaber')
    op.drop_table('mechaber')
    # ### end Alembic commands ###
