"""add Mechaber

Revision ID: be5281e23366
Revises: 
Create Date: 2019-10-20 12:21:28.567864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5281e23366'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechaber',
    sa.Column('mechaber_id', sa.Integer(), nullable=False),
    sa.Column('mechaber_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('mechaber_id')
    )
    op.create_index(op.f('ix_mechaber_mechaber_name'), 'mechaber', ['mechaber_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mechaber_mechaber_name'), table_name='mechaber')
    op.drop_table('mechaber')
    # ### end Alembic commands ###
